baseurl: https://kallangerard.github.io/
copyright: Kallan Gerard
title: Kallan Gerard
defaultContentLanguage: en
languageCode: en-us

googleAnalytics: "UA-176245800-1"

theme: hello-friend-ng
paginate: 10

PygmentsCodeFences: true
PygmentsStyle: "monokai"

archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public

buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: false

enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
enableMissingTranslationPlaceholders: false
disableRSS: false
disableSitemap: false
disable404: false
disableHugoGeneratorInject: false

permalinks: 
  posts: "/posts/:year/:month/:title/"

author: 
  name: Kallan Gerard

disqusShortname: kallangerard

params:
  dateform: "2 Jan, 2006"
  dateformShort: "2 Jan"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"


  homeSubtitle: A simple blog of my technical adventures
  enableSharingButtons: false

  description: "A blog of my lean devops learnings"
  keywords: "homepage, blog"
  images: [""]

  defaultTheme: dark

  Logo:
    logoText: "Kallan Gerard"
    logoHomeLink: "/"
    logoCursorDisabled: true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS: []
  customJS: []
  social:
    - name: linkedin
      url: "https://www.linkedin.com/in/kallan-gerard-2a3266157/"
    - name: github
      url: "https://github.com/kallangerard"

taxonomies:
  category: categories
  tag: tags
  series: series



menu:
  main:
    - identifier: posts
      name: Posts
      url: posts/
    - identifier: reading-list
      name: Reading List
      url: reading-list/
